### ISSUE TITLE
Question about feature

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [SonMooSans/discord-bot-dashboard-backend-ts#1]
Hi we use your dashboard for my project with this backend but dont find who use

```
  getFeature(guild: string): Promise<{
      message: string;
      channel: string | null;
  } | null>;
  enableFeature(req: Request, guild: string): Promise<string>;
  updateFeature(req: Request, guild: string, body: Partial<WelcomeMessage>): Promise<WelcomeMessage>;
  disableFeature(guild: string, req: AuthRequest): Promise<string>;
  getChannels(guild: string): Promise<(import("discord.js").NonThreadGuildBasedChannel | null)[] | null>;
  getRoles(guild: string): Promise<import("discord.js").Role[] | null>;
```

in bot service for check if feature is enable or disable
thx you for your work

**Comment by fuma-nama** [comment]
Hi @Gregory-Hepicloud 
`getFeature` means getting the data of a feature, it returns null if it's disabled

**Comment by fuma-nama** [comment]
If no problem, I will close this issue

**Comment by Gregory-Hepicloud** [comment]
> `getFeature`

The question is who use getFeature in bot service for bot check if Feature is enable? who call him in code

thx for reply
